version: '3'

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - user_service
      - tweet_service

  user_service:
    build: ./user_service
    environment:
      - POSTGRES_DSN=postgres://twitter:secret@postgres:5432/twitter_db
    depends_on:
      - postgres

  tweet_service:
    build: ./tweet_service
    depends_on:
      - kafka
      - cassandra

  realtime_service:
    build: ./realtime_service
    ports:
      - "8081:8081"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    ports:
      - "29092:29092"

  elasticsearch:
    image: elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: twitter
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: twitter_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  postgres_data:
  cassandra_data: